### ISSUE TITLE
Warnings about reflection

### ISSUE THREAD

**Issue by vkuncak** [romac/stainless-plugin-test#2]
Even after fetching artifacts and modifying the example source code, one continues to get this warning:

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/home/kuncak/.sbt/boot/scala-2.12.7/org.scala-sbt/sbt/1.2.8/protobuf-java-3.3.1.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[info] Packaging /home/kuncak/software/a-stainless-plugin-test/target/scala-2.12/stainless-plugin-test_2.12-0.1.0.jar ...

**Comment by romac** [comment]
I am unable to reproduce this issue, unfortunately. Can you be more specific as to which commands you are running?

**Comment by romac** [comment]
Are you having the same issue with the giter8 template at https://github.com/epfl-lara/stainless-project.g8?

**Comment by romac** [comment]
Seems to be an issue with JDK11, which Scala 2.12.8 does not support.
